server:
  port: 80
spring:
  application:
    name: consul-provider-order-123
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
